### ISSUE TITLE
Проблема при использовании 2х адресов на lo интерфейсе

### ISSUE THREAD

**Issue by napaster** [k0ste/ansible-role-frr#1]
Операционная система
```
Linux r2d2 5.6.19-1-nfcustom #1 SMP PREEMPT Thu, 10 Sep 2020 13:01:18 +0000 x86_64 GNU/Linux
```
Версия frr
```
Version         : 7.4-7
```
 ansible --version
 ```
 ansible 2.10.5
```

frr.yml
```
---
frr_settings_interfaces_loopback_address:
- '172.16.255.30/32'
- '172.16.249.4/32'
```
Но в конфигурацию это не попадает, при том что если прописать это руками frr это принимает и адреса на lo интерфейс вешаются.

```
r2d2# sh interface lo 
Interface lo is up, line protocol is up
  Link ups:       0    last: (never)
  Link downs:     0    last: (never)
  vrf: default
  Description: Loopback0
  index 1 metric 0 mtu 65536 speed 0 
  flags: <UP,LOOPBACK,RUNNING>
  Type: Loopback
  inet 172.16.249.4/32
  inet 172.16.255.30/32
  Interface Type Other
  ```

**Comment by k0ste** [comment]
Multiple ip addresses on any interface is already supported, I was added example to README.MD in https://github.com/k0ste/ansible-role-frr/commit/cb538e8b898ff8aaf65f35008196f41d9c366e0e.

```yaml
---
frr:
  - settings:
      - interfaces:
          - name: 'eth0'
            ip:
              - address: '10.10.10.1/32'
              - address: '10.10.11.1/32'
```
